### ISSUE TITLE
Binding context for schedule hook pretend to be a context for kubernetes

### ISSUE THREAD

**Issue by diafour** [flant/addon-operator#122]
Some hooks receive a wrong binding context and error is occurred:

```
schedule       ERROR: Can't find any handler from the list: __on_kubernetes::main, __main__"
```

```
    configVersion: v1
    schedule:
    - name: main
      queue: /modules/$(module::name::kebab_case)/schedul
      crontab: "* * * * *"
      includeSnapshotsFrom: [pods,nodes]
   kubernetes:
   - name: pods
      ...
   - name: nodes
      ...
```
