### ISSUE TITLE
Allow use the external chart for module

### ISSUE THREAD

**Issue by diafour** [flant/addon-operator#153]
The module can have no templates directory and have dependencies in Chart.yaml. The problem is that addon-operator construct values for helm in this form:

```
global:
  globalKey1: ...
  globalKey2: ...
  ...
moduleNameInCamelCase:
  moduleKey1: ...
  moduleKey2: ...
```

But external chart does not "expect" values in this form. Should we define values transformation in `module.yaml` (#39) or there is a better solution for this problem?
