### ISSUE TITLE
Using `exclusiveMaximum` in OpenAPI schema causes an error

### ISSUE THREAD

**Issue by piotrminkina** [flant/addon-operator#370]
**Expected behavior (what you expected to happen)**:
It should be possible to use `exclusiveMaximum` in OpenAPI validation.

**Actual behavior (what actually happened)**:
Using this property causes an error:

```
time="2023-04-03T13:32:01Z" level=error msg="Fatal: init module manager: add global schemas: prepare global schemas: load global 'config' schema: json unmarshal: json: cannot unmarshal number into Go struct field .properties of type bool"
```

**Steps to reproduce**:
1. Create a file `/global-hooks/openapi/config-values.yaml` with the following content:
    ```yaml
    type: object
    additionalProperties: false
    required:
      - number
    properties:
      number:
        type: number
        exclusiveMaximum: 100
    ```
2. Try to start Addon Operator
3. A console log should show the message mentioned above.

**Environment**:
- Addon-operator version: v1.1.2
- Helm version: v3.10.3+g835b733
- Kubernetes version: v1.23.6+k3s1
- Installation type (kubectl apply, helm chart, etc.): Own Helm Chart
