### ISSUE TITLE
Module's helm release in uninstalling state doesn't get purged by the operator

### ISSUE THREAD

**Issue by miklezzzz** [flant/addon-operator#496]
**Expected behavior (what you expected to happen)**:
if a module is disabled, it's helm releases should be purged

**Actual behavior (what actually happened)**:
module was disabled, but it seems the operator couldn't completely delete the module's release and the release ended up in Uninstalling state
```
kind: Secret
metadata:
  creationTimestamp: "2024-08-08T09:22:31Z"
  labels:
    modifiedAt: "1723108936"
    name: virtualization
    owner: helm
    status: uninstalling
    version: "2"
  name: sh.helm.release.v1.virtualization.v2
``` 
Consequent purge calls couldn't remediate the situation, reporting:
```
{"level":"info","msg":"Modules to purge found: []","time":"2024-08-14T14:24:10Z"}
```

**Steps to reproduce**:
1. ...
2. ...
3. ...

**Environment**:
- Addon-operator version:
- Helm version:
- Kubernetes version:
- Installation type (kubectl apply, helm chart, etc.):

**Anything else we should know?**:

**Additional information for debugging (if necessary)**:

<details><summary>Hook script</summary><br><pre>

</pre></details>

<details><summary>Logs</summary><br><pre>

</pre></details>
